version: '3.3'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  # redis:
  #   image: redis/redis-stack-server
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   expose:
  #     - '6379'
  #   volumes:
  #     - my-redis:/data
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  db:
  # my-redis:
